{{- if eq .Values.pod true }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: pod-hpa-test
data:
  pod-test.sh: |- {{ .Files.Get "scripts/pod-test.sh" | nindent 4 }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: pod-hpa-test
spec:
  template:
    spec:
      serviceAccountName: checks
      containers:
        - name: check-loadbalancer-svc
          image: bitnami/kubectl:1.26
          workingDir: /checks
          securityContext:
            allowPrivilegeEscalation: false
            runAsUser: 0
          command: ["/bin/bash", "-c"]
          args:
            - "cp /conf/pod-test.sh ./ && chmod u+x pod-test.sh && ./pod-test.sh"
          volumeMounts:
            - mountPath: /conf
              name: config
          env:
            - name: TESTING_NS
              value: {{ .Release.Namespace }}
      restartPolicy: Never
      volumes:
        - name: config
          configMap:
            name: pod-hpa-test
  backoffLimit: 0
  podFailurePolicy:
    rules:
      - action: FailJob
        onExitCodes:
          operator: In
          values: [ 1 ]
{{- end }}